config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "homes#index"
  get "/about", to: "homes#about"

  get "articles/multi_search", to: "articles#multi_search", as: "multi_search_articles"
  resources :articles, only: %i(index show) do
    member do
      post "authentication_approval"
    end
  end
  resources :categories, only: %i(show)

  get "areas/cities", to: "areas#cities"
  resources :areas, only: %i(show)

  resources :notices, only: %i(index show)
  resources :contacts, only: %i(new create)

  resources :admin_coupons do
    collection do
      get "coupons_detail"
    end
  end
  resources :admin_posts do
    post "upload_content_image", on: :collection
    get "view_counts", on: :member
  end
  resources :admin_categories, only: %i(index new create edit update destroy)
  resources :admin_areas, only: %i(index new create edit update destroy)
  resources :admin_stores do
    get "view_counts", on: :member
  end
  resources :admin_notices
  resources :admin_company_users do
    collection do
      post "bulk_create"
    end
  end

  delete "admin/logout", to: "admin_sessions#destroy", as: :admin_logout
  get "admin/login", to: "admin_sessions#new", as: :admin_login
  post "admin/login", to: "admin_sessions#create"

  # エラーページ用のルート
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
  # match "*path", to: "application#render_404", via: :all
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :admin_company_users, dependent: :destroy
  has_many :store_monthly_post_views, dependent: :destroy
  has_many :business_hours, dependent: :destroy
  accepts_nested_attributes_for :business_hours, allow_destroy: true

  validates :name, presence: true
  validates :address, presence: true
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  before_action :set_store, only: %i(edit update destroy show)

  def index
    @stores = Store.all
  end

  def show; end

  def new
    @store = Store.new
  end

  def edit; end

  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:success] = "店舗情報を追加しました"
    else
      flash[:error] = @store.errors.full_messages
    end
    redirect_to stores_path
  end

  def update
    if @store.update(store_params)
      flash[:success] = "店舗情報を更新しました"
    else
      flash[:error] = @store.errors.full_messages
    end
    redirect_to stores_path
  end

  def destroy
    @store.destroy
    flash[:destroy] = "店舗情報を削除しました"
    redirect_to stores_path
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :tel, :address, :google_map_url, :access, :access2,
                                  :nearest_station, :nearest_station2, :sales_time_lanch_weekday,
                                  :sales_time_lanch_holiday, :sales_time_dinner_weekday,
                                  :sales_time_dinner_holiday, :holiday, :pay_methods, :homepage_url,
                                  :sns_link_tabelog, :sns_link_twitter, :sns_link_instagram,
                                  :sns_link_facebook, :sns_link_line)
  end
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with model: @store do |f| %>
  <%= render 'shared/error_messages'%>

  <div class="mt-1">
    <%= f.label :name, "店舗名" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_field :name, class: 'form-control', required: true %>
    <span class="input_example">入力例：株式会社テスト</span>
  </div>
  <div class="mt-1">
    <%= f.label :tel, "電話番号" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.telephone_field :tel, class: 'form-control', required: true %>
    <span class="input_example">入力例：000-1111-3333　※ハイフンを含めて入力してください。</span>
  </div>
  <div class="mt-1">
    <%= f.label :address, "住所" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_field :address, class: 'form-control', required: true %>
    <span class="input_example">入力例：〒000-111 東京都品川区高輪テスト1-1　※郵便番号も含めて全て入力してください。</span>
  </div>
  <div class="mt-1">
    <%= f.label :google_map_url, "住所 Google MapのURL" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_field :google_map_url, class: 'form-control', required: true %>
    <span class="input_example">※ 該当住所のGoogle Mapを開く → 「共有」をクリック → 「地図を埋め込む」 → 「HTMLをコピーをクリック」</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "徒歩 アクセス方法" %>
    <%= f.text_field :access, class: 'form-control' %>
    <span class="input_example">入力例：相模原線 橋本駅から徒歩10分</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "バス アクセス方法" %>
    <%= f.text_field :access2, class: 'form-control' %>
    <span class="input_example">入力例：小田急 相模大野駅からバス9分</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "最寄駅" %>
    <%= f.text_field :nearest_station, class: 'form-control' %>
    <span class="input_example">入力例：相模原線 橋本駅</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "最寄駅２" %>
    <%= f.text_field :nearest_station2, class: 'form-control' %>
    <span class="input_example">入力例：相模原線 橋本駅</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "営業時間 ランチ平日" %>
    <%= f.text_field :sales_time_lanch_weekday, class: 'form-control' %>
    <span class="input_example">入力例：平日 11:30 ～ 15:00 (13:00)</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "営業時間 ランチ土日祝" %>
    <%= f.text_field :sales_time_lanch_holiday, class: 'form-control' %>
    <span class="input_example">入力例：土日祝 12:00 ～ 15:00 (13:00)</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "営業時間 ディナー平日" %>
    <%= f.text_field :sales_time_dinner_weekday, class: 'form-control' %>
    <span class="input_example">入力例：18:00 ～ 22:00 (20:00)</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "営業時間 ディナー土日祝" %>
    <%= f.text_field :sales_time_dinner_holiday, class: 'form-control' %>
    <span class="input_example">入力例：18:00 ～ 22:00 (20:00)</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "定休日" %>
    <%= f.text_field :holiday, class: 'form-control' %>
    <span class="input_example">入力例：水曜日、第1・3火曜日</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "支払い方法" %>
    <%= f.text_field :pay_methods, class: 'form-control' %>
    <span class="input_example">入力例：PayPay,楽天ペイ,現金,クレジットカード,交通系IC,メルペイ,PayPal,暗号通貨</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "ホームページURL" %>
    <%= f.text_field :homepage_url, class: 'form-control' %>
    <span class="input_example">入力例：https://www.google.com/</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "食べログリンク" %>
    <%= f.text_field :sns_link_tabelog, class: 'form-control' %>
    <span class="input_example">入力例：https://tabelog.com/</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "ツイッターリンク" %>
    <%= f.text_field :sns_link_twitter, class: 'form-control' %>
    <span class="input_example">入力例：https://twitter.com/?lang=ja</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "インスタグラム" %>
    <%= f.text_field :sns_link_instagram, class: 'form-control' %>
    <span class="input_example">入力例：https://www.instagram.com/</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "フェースブック" %>
    <%= f.text_field :sns_link_facebook, class: 'form-control' %>
    <span class="input_example">入力例：https://facebook.com/</span>
  </div>
  <div class="mt-1">
    <%= f.label :name, "LINEリンク" %>
    <%= f.text_field :sns_link_line, class: 'form-control' %>
    <span class="input_example">入力例：https://line.me/ja/</span>
  </div>

  <div class="mb-4">
    <%= link_to '戻る', stores_path, data: {turbo: false}, class: 'btn btn-warning mt-2' %>
    <%= f.submit '更新', data: {turbo: false}, class: 'btn btn-info mt-2' %>  
  </div>
<% end %>

app/views/stores/index.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1 class="mb-3">店舗情報一覧</h1>

<%= link_to '新しい店舗を追加', new_store_path, data: {turbo: false}, class: 'btn btn-primary mb-3' %>
<% if flash[:success].present? %>
  <div class="alert alert-success text-center mt-2">
    <%= flash[:success].html_safe %>
  </div>
<% elsif flash[:destroy].present? %>
  <div class="alert alert-danger text-center">
    <%= flash[:destroy].html_safe %>
  </div>
<% end %>
<table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr>
      <th>店舗名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td>
          <%= link_to '詳細', store_path(store), data: {turbo: false}, class: 'btn btn-sm btn-success me-2' %> 
          <%= link_to '編集', edit_store_path(store), data: {turbo: false}, class: 'btn btn-sm btn-warning me-2' %> 
          <%= link_to '削除', store_path(store), data: { "turbo-method": :delete, turbo_confirm: "削除しますか？" }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/show.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1>店舗情報詳細</h1>

<div class="mt-4">
  <table class="table table-striped table-bordered">
    <tbody>
      <tr>
        <th>店舗名</th>
        <td><%= @store.name %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @store.tel %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @store.address %></td>
      </tr>
      <tr>
        <th>徒歩 アクセス方法</th>
        <td><%= @store.access %></td>
      </tr>
      <tr>
        <th>バス アクセス方法</th>
        <td><%= @store.access2 %></td>
      </tr>
      <tr>
        <th>最寄駅</th>
        <td><%= @store.nearest_station %></td>
      </tr>
      <tr>
        <th>最寄駅２</th>
        <td><%= @store.nearest_station2 %></td>
      </tr>
      <tr>
        <th>営業時間 ランチ平日</th>
        <td><%= @store.sales_time_lanch_weekday %></td>
      </tr>
      <tr>
        <th>営業時間 ランチ土日祝</th>
        <td><%= @store.sales_time_lanch_holiday %></td>
      </tr>
      <tr>
        <th>営業時間 ディナー平日</th>
        <td><%= @store.sales_time_dinner_weekday %></td>
      </tr>
      <tr>
        <th>営業時間 ディナー土日祝</th>
        <td><%= @store.sales_time_dinner_holiday %></td>
      </tr>
      <tr>
        <th>定休日</th>
        <td><%= @store.holiday %></td>
      </tr>
      <tr>
        <th>支払い方法</th>
        <td><%= @store.pay_methods %></td>
      </tr>
      <tr>
        <th>ホームページURL</th>
        <td><%= @store.homepage_url %></td>
      </tr>
      <tr>
        <th>食べログリンク</th>
        <td><%= @store.sns_link_tabelog %></td>
      </tr>
      <tr>
        <th>ツイッターリンク</th>
        <td><%= @store.sns_link_twitter %></td>
      </tr>
      <tr>
        <th>インスタグラム</th>
        <td><%= @store.sns_link_instagram %></td>
      </tr>
      <tr>
        <th>フェースブック</th>
        <td><%= @store.sns_link_facebook %></td>
      </tr>
      <tr>
        <th>LINEリンク</th>
        <td><%= @store.sns_link_line %></td>
      </tr>
    </tbody>
  </table>

  <div class="mb-4">
    <%= link_to '戻る', stores_path, data: {turbo: false}, class: 'btn btn-warning mt-2' %>
  </div>
</div>