config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "homes#index"
  get "/about", to: "homes#about"

  get "articles/multi_search", to: "articles#multi_search", as: "multi_search_articles"
  resources :articles, only: %i(index show) do
    member do
      post "authentication_approval"
    end
  end
  resources :categories, only: %i(show)

  get "areas/cities", to: "areas#cities"
  resources :areas, only: %i(show)

  resources :notices, only: %i(index show)
  resources :contacts, only: %i(new create)

  resources :admin_coupons do
    collection do
      get "coupons_detail"
    end
  end
  resources :admin_posts do
    post "upload_content_image", on: :collection
    get "view_counts", on: :member
  end
  resources :admin_categories, only: %i(index new create edit update destroy)
  resources :admin_areas, only: %i(index new create edit update destroy)
  resources :admin_stores do
    get "view_counts", on: :member
  end
  resources :admin_notices
  resources :admin_company_users do
    collection do
      post "bulk_create"
    end
  end

  delete "admin/logout", to: "admin_sessions#destroy", as: :admin_logout
  get "admin/login", to: "admin_sessions#new", as: :admin_login
  post "admin/login", to: "admin_sessions#create"

  # エラーページ用のルート
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
  # match "*path", to: "application#render_404", via: :all
end

app/controllers/admin_notices_controller.rb
# frozen_string_literal: true

class AdminNoticesController < ApplicationController
  before_action :set_notice, only: %i(edit update destroy)
  before_action :authenticate_user, :redirect_not_logged_in, :redirect_not_session, :set_session_expiration

  def index
    @notices = Notice.all
  end

  def new
    @notice = Notice.new
  end

  def edit; end

  def create
    @notice = Notice.new(notice_params)
    if @notice.save
      flash[:success] = "エリアを追加しました"
    else
      flash[:error] = @notice.errors.full_messages
    end
    redirect_to admin_notices_path
  end

  def update
    if @notice.update(notice_params)
      flash[:success] = "エリアを更新しました"
    else
      flash[:error] = @notice.errors.full_messages
    end
    redirect_to admin_notices_path
  end

  def destroy
    @notice.destroy
    flash[:destroy] = "エリアを削除しました"
    redirect_to admin_notices_path, notice: "エリアを削除しました"
  end

  private

  def set_notice
    @notice = Notice.find(params[:id])
  end

  def notice_params
    params.require(:notice).permit(:title, :kind, :content)
  end
end

app/helpers/admin_notices_helper.rb
# frozen_string_literal: true

module AdminNoticesHelper
end

app/views/admin_notices/_form.html.erb
<%= form_with model: @notice, url: (@notice.new_record? ? admin_notices_path : admin_notice_path(@notice)) do |f| %>

  <%= render 'shared/error_messages'%>

  <!-- タイトル -->
  <div class="form-group">
    <%= f.label :title, "タイトル", class: "mb-1 mt-3" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <!-- お知らせ内容 -->
  <div class="form-group">
    <%= f.label :content, "お知らせ内容", class: "mb-1 mt-3" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_area :content, class: "form-control", id: "note_explanation", rows: "20", placeholder: "投稿内容を入力してください", required: true %>
  </div>

  <!-- 種類 -->
  <div class="form-group">
    <%= f.label :kind, "種類", class: "mb-1 mt-3" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.select :kind, [[ "お知らせ", 1 ], [ "リリース", 2 ]], {}, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= link_to '戻る', admin_notices_path, class: 'btn btn-warning mt-2' %>
    <%= f.submit '更新', class: 'btn btn-info mt-2' %>  
  </div>
<% end %>

app/views/admin_notices/edit.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1>お知らせを編集</h1>
<%= render 'form' %>

app/views/admin_notices/index.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1 class="mb-3">お知らせ一覧</h1>

<%= link_to '新しいお知らせを追加', new_admin_notice_path, class: 'btn btn-primary mb-3' %>
<% if flash[:success].present? %>
  <div class="alert alert-success text-center mt-2">
    <%= flash[:success].html_safe %>
  </div>
<% elsif flash[:destroy].present? %>
  <div class="alert alert-danger text-center">
    <%= flash[:destroy].html_safe %>
  </div>
<% end %>

<table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr>
      <th>日付</th>
      <th>お知らせタイトル</th>
      <th>種類</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.created_at.strftime('%Y/%m/%d %H:%M:%S管理者ログイン管理者ログイン') %></td>
        <td><%= notice.title %></td>
        <td><%= notice.kind == 1 ? "お知らせ" : (notice.kind == 2 ? "リリース" : "未知") %></td>
        <td>
          <%= link_to '編集', edit_admin_notice_path(notice), class: 'btn btn-sm btn-warning me-2' %> 
          <%= link_to '削除', admin_notice_path(notice), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin_notices/new.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1>新しいお知らせを追加</h1>
<%= render 'form' %>