config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "homes#index"
  get "/about", to: "homes#about"

  get "articles/multi_search", to: "articles#multi_search", as: "multi_search_articles"
  resources :articles, only: %i(index show) do
    member do
      post "authentication_approval"
    end
  end
  resources :categories, only: %i(show)

  get "areas/cities", to: "areas#cities"
  resources :areas, only: %i(show)

  resources :notices, only: %i(index show)
  resources :contacts, only: %i(new create)

  resources :admin_coupons do
    collection do
      get "coupons_detail"
    end
  end
  resources :admin_posts do
    post "upload_content_image", on: :collection
    get "view_counts", on: :member
  end
  resources :admin_categories, only: %i(index new create edit update destroy)
  resources :admin_areas, only: %i(index new create edit update destroy)
  resources :admin_stores do
    get "view_counts", on: :member
  end
  resources :admin_notices
  resources :admin_company_users do
    collection do
      post "bulk_create"
    end
  end

  delete "admin/logout", to: "admin_sessions#destroy", as: :admin_logout
  get "admin/login", to: "admin_sessions#new", as: :admin_login
  post "admin/login", to: "admin_sessions#create"

  # エラーページ用のルート
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
  # match "*path", to: "application#render_404", via: :all
end

app/views/shared/_admin_header.html.erb
<div class="col-md-3">
  <div class="list-group mb-2">
    <% if current_company_admin? %>
      <%= active_link_to '投稿一覧', admin_posts_path, class: "list-group-item list-group-item-action" %>
      <%= active_link_to '店舗情報一覧', admin_stores_path,  class: "list-group-item list-group-item-action" %>
    <% else %>
      <%= active_link_to '投稿一覧', admin_posts_path, class: "list-group-item list-group-item-action" %>
      <%= active_link_to 'カテゴリー一覧', admin_categories_path,  class: "list-group-item list-group-item-action" %>
      <%= active_link_to 'エリア一覧', admin_areas_path,  class: "list-group-item list-group-item-action" %>
      <%= active_link_to '店舗情報一覧', admin_stores_path,  class: "list-group-item list-group-item-action" %>
      <%= active_link_to 'お知らせ一覧', admin_notices_path,  class: "list-group-item list-group-item-action" %>
      <% if current_admin&.login_id == "admin001" %>
        <%= active_link_to '会社ごとのアカウント作成', admin_company_users_path,  class: "list-group-item list-group-item-action" %>
      <% end %>
    <% end %>
    <%= link_to 'ログアウト', admin_logout_path, method: :delete, class: "list-group-item list-group-item-action" %>
  </div>
</div>

app/views/shared/_areas.html.erb
<div class="common_title">
  <h3>
    AREA <span>エリア</span>
  </h3>
</div>

<% if areas.present? %>
  <div class="area_list">
    <% areas.uniq { |area| area.name }.each do |area| %>
      <%= link_to area_path(area) do %>
        <span><%= area.name %></span>
        <%= image_tag "#{area.name}.webp", alt: "#{area.name}の風景" %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="not_content">エリアがひとつもありません。</p>
<% end %>

app/views/shared/_categories.html.erb
<div class="common_title">
  <h3>
    CATEGORY <span>カテゴリー</span>
  </h3>
</div>
<% if categories.present? %>
  <div class="tag_list">
    <% categories.each do |category| %>
      <%= link_to category.name, category_path(category) %>
    <% end %>
  </div>
<% else %>
  <p class="not_content">カテゴリーがひとつもありません。</p>
<% end %>

app/views/shared/_coupon.html.erb
<% if coupons.present? %>
  <% coupons.each do |coupon| %>
    <div class="coupon_edit_btn">
      <%= link_to '編集', edit_admin_coupon_path(coupon, coupon_type: coupon&.coupon_type_id), class: 'btn btn-warning' %>
      <%= link_to '削除', admin_coupon_path(coupon), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger delete-coupon' %>
    </div>
    <div class="coupon mb-3">
      <div class="left">
        <div class="coupon_tag_title">
          <div class="coupon_tag">
            <%= image_tag 'coupon.svg' %>
          </div>
          <p>クーポン</p>
        </div>
        <div class="left_top">
          <h3><%= coupon&.title %></h3>
        </div>
        <div class="left_bottom">
          <div class="coupon_term_part">
            <p class="left_bottom_left">利用条件</p>
            <p class="left_bottom_right"><%= coupon&.usage_terms&.gsub(",", " / ") %></p>
          </div>
          <div class="coupon_term_part">
            <p class="left_bottom_left">提示条件</p>
            <p class="left_bottom_right"><%= coupon&.presentation_terms&.gsub(",", " / ") %></p>
          </div>
        </div>
      </div>
      <div class="right">
          <div class="right-inner">
              <div class="date">
                <span class="expiration_date_title">有効期限</span>
                <p><%= get_coupon_expiration_data coupon %></p>
              </div>
          </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="coupon">
    <div class="left">
      <div class="coupon_tag_title">
        <div class="coupon_tag">
          <%= image_tag 'coupon.svg' %>
        </div>
        <p>クーポン</p>
      </div>
      <div class="left_top">
        <h3></h3>
      </div>
      <div class="left_bottom">
        <div class="coupon_term_part">
          <p class="left_bottom_left">利用条件</p>
          <p class="left_bottom_right"></p>
        </div>
        <div class="coupon_term_part">
          <p class="left_bottom_left">提示条件</p>
          <p class="left_bottom_right"></p>
        </div>
      </div>
    </div>
    <div class="right">
        <div class="right-inner">
            <div class="date">
              <span class="expiration_date_title">有効期限</span>
              <p></p>
            </div>
        </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% flash[:error].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="footer_img">
      <%= image_tag "1.png", alt: "日常街のポータル" %>
    </div>
    <ul class="nav_menu footer_menu">
      <li><%= link_to "日常街のポータルとは", about_path %></li>
      <li><%= link_to "おすすめ", articles_path(type: 'recommend') %></li>
      <li><%= link_to "新着記事", articles_path(type: 'news') %></li>
      <li><%= link_to "お知らせ", notices_path %></li>
    </ul>
    <div class="footer_content">
      <p>©︎ 日常街のポータル - All Rights Resered</p>
      <% if params[:id].present? && request.fullpath.include?('articles') %>
        <div class="edit_switch_content">
          <label class="switch">
            <input type="checkbox" id="toggleSwitch">
            <span class="slider round"></span>
          </label>
          <span class="edit_s">編集</span>
        </div>
      <% end %>
    </div>
  </div>
</footer>

<% if params[:id].present? && request.fullpath.include?('articles') %>
  <!-- モーダルウィンドウのマークアップ -->
  <div id="loginModal" class="modal">
    <div class="modal-content">
      <span class="close-button">×</span>
      <%= form_with url: authentication_approval_article_path(params[:id]), local: false, remote: true do |form| %>
        <fieldset>
          <div class="authentication_content">
            <%= form.label :authentication_code, "認証コード" %>
            <%= form.text_field :authentication_code, required: true %>
          </div>
          <%= form.submit "認証", class: "authentication_submit" %>
        </fieldset>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="header">
    <div class="header_left">
      <%= link_to root_path do %>
        <%= image_tag "1.png", alt: "日常街のポータル" %>
      <% end %>
    </div>
    <div class="header_right">
      <ul class="nav_menu">
        <li class="store_request">
          <%= link_to "店舗掲載依頼する", "https://docs.google.com/forms/d/1Tp1E_CNcpD-no-avT4etZC0mPVRXjb2q86CUSaFPOgU/prefill", target: '_blank', rel: 'noopener noreferrer' %>
          <div class="store_request_arrow">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.46 18.0002C10.1459 17.9993 9.83558 17.9311 9.55 17.8002C9.24083 17.6639 8.97741 17.4415 8.79122 17.1596C8.60503 16.8776 8.50393 16.548 8.5 16.2102V7.79019C8.50393 7.45234 8.60503 7.12276 8.79122 6.84081C8.97741 6.55886 9.24083 6.33647 9.55 6.20019C9.90574 6.03216 10.3015 5.96744 10.6923 6.01341C11.083 6.05938 11.453 6.21419 11.76 6.46019L16.86 10.6702C17.06 10.8294 17.2215 11.0317 17.3325 11.2619C17.4435 11.4922 17.5012 11.7446 17.5012 12.0002C17.5012 12.2558 17.4435 12.5082 17.3325 12.7384C17.2215 12.9687 17.06 13.171 16.86 13.3302L11.76 17.5402C11.3924 17.8383 10.9333 18.0008 10.46 18.0002Z" fill="white"/>
            </svg>
          </div>
        </li>
        <li class="<%= 'active_header_menu' if current_page?(about_path) %>">
          <%= link_to "日常街のポータルとは", about_path %>
        </li>
        <li class="<%= 'active_header_menu' if controller_name == 'articles' && params[:type] == 'recommend' %>">
          <%= link_to "おすすめ", articles_path(type: 'recommend') %>
        </li>
        <li class="<%= 'active_header_menu' if controller_name == 'articles' && params[:type] == 'news' %>">
          <%= link_to "新着記事", articles_path(type: 'news') %>
        </li>
        <li class="<%= 'active_header_menu' if current_page?('#') %>">
          <%= link_to "お知らせ", notices_path %>
        </li>
      </ul>
    </div>
    <div class="header_right_mobile">
      <li class="store_request">
        <%= link_to "店舗掲載依頼する", "https://docs.google.com/forms/d/1Tp1E_CNcpD-no-avT4etZC0mPVRXjb2q86CUSaFPOgU/prefill", target: '_blank', rel: 'noopener noreferrer' %>
        <div class="store_request_arrow">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10.46 18.0002C10.1459 17.9993 9.83558 17.9311 9.55 17.8002C9.24083 17.6639 8.97741 17.4415 8.79122 17.1596C8.60503 16.8776 8.50393 16.548 8.5 16.2102V7.79019C8.50393 7.45234 8.60503 7.12276 8.79122 6.84081C8.97741 6.55886 9.24083 6.33647 9.55 6.20019C9.90574 6.03216 10.3015 5.96744 10.6923 6.01341C11.083 6.05938 11.453 6.21419 11.76 6.46019L16.86 10.6702C17.06 10.8294 17.2215 11.0317 17.3325 11.2619C17.4435 11.4922 17.5012 11.7446 17.5012 12.0002C17.5012 12.2558 17.4435 12.5082 17.3325 12.7384C17.2215 12.9687 17.06 13.171 16.86 13.3302L11.76 17.5402C11.3924 17.8383 10.9333 18.0008 10.46 18.0002Z" fill="white"/>
          </svg>
        </div>
      </li>
      <div id="nav-icon">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <ul id="mobile-nav">
        <li><%= link_to "日常街のポータルとは", about_path %></li>
        <li><%= link_to "おすすめ", articles_path(type: 'recommend') %></li>
        <li><%= link_to "新着記事", articles_path(type: 'news') %></li>
        <li><%= link_to "お知らせ", notices_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_multi_search.html.erb
<%= form_with url: multi_search_articles_path, method: :get, local: true, id: "search-form", class: "search-form pc_search_form" do %>
  <div class="form-group">
    <label for="prefecture">都道府県<span>から探す</span></label>
    <%= select_tag :prefecture, options_for_select(Area.unique_prefectures, params[:prefecture]), include_blank: "選択してください", id: "prefecture", class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="city">市区町村<span>から探す</span></label>
    <%= select_tag :city, options_for_select([], params[:city]), include_blank: "都道府県を選択してください", id: "city", class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="category">ジャンル<span>から探す</span></label>
    <%= select_tag :category, options_for_select(Category.order_categoies, params[:category]), include_blank: "選択してください", id: "category", class: "form-control" %>
  </div>
  <%= submit_tag 'この条件で検索する', class: 'search-button btn btn-primary' %>
<% end %>

app/views/shared/_pc_multi_search.html.erb
<%= form_with url: multi_search_articles_path, method: :get, local: true, id: "search-form", class: "search-form pc_search_form" do %>
  <div class="form-group">
    <label for="prefecture">都道府県<span>から探す</span></label>
    <%= select_tag :prefecture, options_for_select(Area.unique_prefectures, params[:prefecture]), include_blank: "選択してください", id: "prefecture", class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="city">市区町村<span>から探す</span></label>
    <%= select_tag :city, options_for_select([], params[:city]), include_blank: "都道府県を選択してください", id: "city", class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="category">ジャンル<span>から探す</span></label>
    <%= select_tag :category, options_for_select(Category.order_categoies, params[:category]), include_blank: "選択してください", id: "category", class: "form-control" %>
  </div>
  <%= submit_tag 'この条件で検索する', class: 'search-button btn btn-primary' %>
  <%= button_tag 'クリア', type: 'button', class: 'clear-button btn btn-secondary', id: "reset-button" %>
<% end %>

app/views/shared/_ranking.html.erb
<div class="ranking">
  <div class="common_title">
    <h3>
      Ranking <span>ランキング</span>
    </h3>
  </div>
  <% if ranking_articles.present? %>
    <div class="ranking_content">
      <% ranking_articles.each.with_index(1) do |ranking_article, idx|  %>
        <%= link_to article_path(ranking_article), class: "ranking_content_part" do %>
          <div class="ranking_left_img">
            <span><%= image_tag "ranking_#{idx}.svg", alt: "ランキング#{idx}" %></span>
            <%= image_tag ranking_article&.top_image if ranking_article.top_image.attached? %>
          </div>
          <div class="ranking_right_content">
            <p class="ranking_article"><%= truncate_content(ranking_article&.title, 30) %></p>
            <% if ranking_article.category.present? %>
              <p class="tag"><%= ranking_article.category.name  %></p>
            <% end %>
            <div class="clock">
              <div class="clock_img">
                <%= image_tag "clock.svg", alt: "時計アイコン" %>
              </div>
              <p><%= ranking_article&.created_at.strftime("%Y/%m/%d") %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <p class="not_content">記事がひとつもありません。</p>
  <% end %>
</div>

app/views/shared/_search_form.html.erb
<%= form_with url: articles_path, method: :get, id: "search_form" do |form| %>
  <div class="search_container">
    <%= form.text_field :search_item, id: "search_input", placeholder: "記事の検索" %>
    <span id="search_icon">
      <%= image_tag "search.svg", alt: "検索画像" %>
    </span>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<%= render partial: "shared/pc_multi_search" %>
<%= render partial: "shared/ranking", locals: { ranking_articles: @ranking_articles } %>
<%= render partial: "shared/search_form" %>

app/views/shared/_sp_multi_search.html.erb
<div id="search-overlay" style="display:none;">
  <button id="close-search">&times;</button>
  <%= form_with url: multi_search_articles_path, method: :get, local: true, id: "search-form", class: "search-form sp_search_form" do %>
    <div class="form-group">
      <label for="prefecture">都道府県<span>から探す</span></label>
      <%= select_tag :prefecture, options_for_select(Area.unique_prefectures, params[:prefecture]), include_blank: "選択してください", id: "prefecture", class: "form-control" %>
    </div>

    <div class="form-group">
      <label for="city">市区町村<span>から探す</span></label>
      <%= select_tag :city, options_for_select([], params[:city]), include_blank: "都道府県を選択してください", id: "city", class: "form-control" %>
    </div>

    <div class="form-group">
      <label for="category">ジャンル<span>から探す</span></label>
      <%= select_tag :category, options_for_select(Category.order_categoies, params[:category]), include_blank: "選択してください", id: "category", class: "form-control" %>
    </div>
    <%= submit_tag 'この条件で検索する', class: 'search-button btn btn-primary' %>
    <%= button_tag 'クリア', type: 'button', class: 'clear-button btn btn-secondary', id: "reset-button" %>
  <% end %>
</div>