config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "homes#index"
  get "/about", to: "homes#about"

  get "articles/multi_search", to: "articles#multi_search", as: "multi_search_articles"
  resources :articles, only: %i(index show) do
    member do
      post "authentication_approval"
    end
  end
  resources :categories, only: %i(show)

  get "areas/cities", to: "areas#cities"
  resources :areas, only: %i(show)

  resources :notices, only: %i(index show)
  resources :contacts, only: %i(new create)

  resources :admin_coupons do
    collection do
      get "coupons_detail"
    end
  end
  resources :admin_posts do
    post "upload_content_image", on: :collection
    get "view_counts", on: :member
  end
  resources :admin_categories, only: %i(index new create edit update destroy)
  resources :admin_areas, only: %i(index new create edit update destroy)
  resources :admin_stores do
    get "view_counts", on: :member
  end
  resources :admin_notices
  resources :admin_company_users do
    collection do
      post "bulk_create"
    end
  end

  delete "admin/logout", to: "admin_sessions#destroy", as: :admin_logout
  get "admin/login", to: "admin_sessions#new", as: :admin_login
  post "admin/login", to: "admin_sessions#create"

  # エラーページ用のルート
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
  # match "*path", to: "application#render_404", via: :all
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
  validates :name, presence: true

  # 都道府県のユニークなリストを取得するメソッド
  def self.order_categoies
    Category.order(:id).pluck(:name)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :load_data, only: %i(show)

  # ページネーションの設定
  def show
    @category = Category.where(id: params[:id]).select(:id, :name).first
    @category_name = if @category.present?
                       @category.name
                     else
                       "存在しないカテゴリー"
                     end
    @articles = fetch_posts
      .where(category_id: @category&.id)
      .order(created_at: :asc)
      .page(params[:page]).per(24)
  end

  private

  # 共通データのロードを１つのメソッドに集約
  def load_data
    @ranking_articles = fetch_posts.includes(:category).by_view_count.limit(5)
    @categories = Category.all
    @areas = Area.all
  end

  # 投稿を取得する共通の処理をメソッドに抽出
  def fetch_posts
    Post.includes(top_image_attachment: :blob)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <%= render 'shared/error_messages'%>

  <div>
    <%= f.label :name, "カテゴリ名" %>
    <span class="badge bg-danger form_require">必須項目</span>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-4">
    <%= link_to '戻る', categories_path, data: {turbo: false}, class: 'btn btn-warning mt-2' %>
    <%= f.submit '更新', data: {turbo: false}, class: 'btn btn-info mt-2' %>  
  </div>
<% end %>

app/views/categories/index.html.erb
<%= stylesheet_link_tag "admin_index" %>

<h1 class="mb-3">カテゴリ一覧</h1>

<%= link_to '新しいカテゴリを追加', new_category_path, data: {turbo: false}, class: 'btn btn-primary mb-3' %>
<% if flash[:success].present? %>
  <div class="alert alert-success text-center mt-2">
    <%= flash[:success].html_safe %>
  </div>
<% elsif flash[:destroy].present? %>
  <div class="alert alert-danger text-center">
    <%= flash[:destroy].html_safe %>
  </div>
<% end %>
<table class="table table-bordered table-hover">
  <thead class="table-light">
    <tr>
      <th>カテゴリ名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to '編集', edit_category_path(category), data: {turbo: false}, class: 'btn btn-sm btn-warning me-2' %> 
          <%= link_to '削除', category_path(category), data: { "turbo-method": :delete, turbo_confirm: "削除しますか？" }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/show.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "shared/hamburger" %>
  <%= javascript_import_module_tag "shared/search" %>
<% end %>


<% assign_meta_tags title: "#{seo_title @category_name}",
                    description: "#{seo_description @category_name}",
                    keywords: "#{@article&.category&.name}" %>

<main>
  <div class="front_main_container">
    <p class="pankuzu">
      <%= link_to 'ホーム', root_path, class: 'common_a' %>
      >
      <%= @category_name %>の記事一覧
    </p>
    <div class="main_content">
      <section class="content_left">
        <div class="news">
          <div class="common_title">
            <h2>
              <%= @category_name %><span>による検索結果</span>
            </h2>
          </div>
          <% if @articles.present? %>
            <div class="common_content">
              <% @articles.each do |article| %>
                <%= link_to article_path(article), class: 'common_content_part' do %>
                  <div class="image_part">
                    <%= image_tag article.top_image if article.top_image.attached? %>
                  </div>
                  <p><%= truncate_content(article.title, 31) %></p>
                  <p><%= article.created_at.strftime("%Y/%m/%d") %></p>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <p class="not_content">記事がひとつもありません。</p>
          <% end %>

          <%= paginate @articles, theme: 'category_article_custom_paginator' %>
        </div>
      </section>
      <aside class="content_right">
        <%= render partial: "shared/sidebar", locals: { 
          ranking_areas: @ranking_areas,
          categories: @categories,
          areas: @areas 
        } %>
      </aside>
    </div>
  </div>
</main>